// AppForge power tools: share setups, saved local setup, new-PC/creator presets and update command.
(function(){
  const refresh=()=>{try{saveSelection();renderApps();updateSelectionBar()}catch(e){console.warn(e)}};
  function setKeys(keys){selected.clear();const allowed=new Set(availableApps().map(a=>a.key));keys.filter(k=>allowed.has(k)).forEach(k=>selected.add(k));refresh()}
  function applyTag(tag){setKeys(availableApps().filter(a=>a.tags?.includes(tag)).map(a=>a.key))}
  function addPowerButtons(){const presets=document.querySelector('.quick-presets');if(!presets||document.querySelector('#newPcPreset'))return;const defs=[['newPcPreset','🖥 New PC',()=>setKeys(availableApps().filter(a=>a.tags?.includes('essentials')||a.popular>=10).map(a=>a.key))],['creatorPreset','🎨 Creator',()=>applyTag('creator')]];for(const [id,text,fn] of defs){const b=document.createElement('button');b.id=id;b.className='preset-btn';b.textContent=text;b.addEventListener('click',fn);presets.insertBefore(b,document.querySelector('#clearSelection'))}}
  function shareUrl(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('os',platform);u.searchParams.set('apps',[...selected].join(','));return u.toString()}
  async function copyText(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='✓ Copied';setTimeout(()=>button.textContent=old,1500)}catch{prompt('Copy this:',text)}}
  function addDialogTools(){const card=document.querySelector('.dialog-card');if(!card||document.querySelector('#shareSetup'))return;const box=document.createElement('div');box.className='command-option';box.innerHTML='<strong>Setup tools</strong><p>Share this exact app list or save it on this device.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="shareSetup" class="command-copy">🔗 Copy share link</button><button id="saveSetup" class="command-copy">💾 Save setup</button><button id="loadSetup" class="command-copy">↻ Load saved</button><button id="updateCommand" class="command-copy">↑ Copy Update All command</button></div><small>Saved setups stay only in this browser. No AppForge account is required.</small>';
    const privacy=card.querySelector('.privacy-note');card.insertBefore(box,privacy);
    box.querySelector('#shareSetup').onclick=e=>copyText(shareUrl(),e.currentTarget);
    box.querySelector('#saveSetup').onclick=e=>{localStorage.setItem(`appforge-saved-${platform}`,JSON.stringify([...selected]));const b=e.currentTarget,old=b.textContent;b.textContent='✓ Saved';setTimeout(()=>b.textContent=old,1500)};
    box.querySelector('#loadSetup').onclick=e=>{try{setKeys(JSON.parse(localStorage.getItem(`appforge-saved-${platform}`)||'[]'));const b=e.currentTarget,old=b.textContent;b.textContent='✓ Loaded';setTimeout(()=>b.textContent=old,1500)}catch{}};
    box.querySelector('#updateCommand').onclick=e=>{const cmd=platform==='windows'?'winget upgrade --all --silent --accept-package-agreements --accept-source-agreements --disable-interactivity':platform==='linux'?'flatpak update -y':'brew update && brew upgrade';copyText(cmd,e.currentTarget)};
  }
  function loadShared(){const q=new URLSearchParams(location.search),keys=(q.get('apps')||'').split(',').filter(Boolean),os=q.get('os');if(!keys.length)return;if(os&&['windows','linux','mac'].includes(os)&&os!==platform){const btn=document.querySelector(`.platform-btn[data-platform="${os}"]`);if(btn)btn.click()}setTimeout(()=>setKeys(keys),0)}
  function addCommunity(){const trust=document.querySelector('.trust-section');if(!trust||document.querySelector('#communityTools'))return;const d=document.createElement('div');d.id='communityTools';d.style.cssText='grid-column:1/-1;display:flex;gap:8px;flex-wrap:wrap;padding-top:6px';d.innerHTML='<a class="command-copy" href="https://github.com/eliron8565/beder-then-ninite" target="_blank" rel="noopener">★ GitHub</a><a class="command-copy" href="https://github.com/eliron8565/beder-then-ninite/issues/new" target="_blank" rel="noopener">＋ Request an app / Report bug</a>';trust.appendChild(d)}
  addPowerButtons();addDialogTools();addCommunity();loadShared();
  document.querySelector('#reviewButton')?.addEventListener('click',()=>setTimeout(addDialogTools,0));
})();