using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace AppForgeInstaller;

internal static class Program
{
    [STAThread] static void Main(){ApplicationConfiguration.Initialize();Application.Run(new MainForm());}
}

internal enum AppHealth { Unknown, Missing, Current, Update, Manual, Failed }
internal sealed record AppItem(int Index,string Name,string PackageId,string IconUrl);

internal sealed class MainForm : Form
{
    readonly FlowLayoutPanel appList=new(); readonly ProgressBar overall=new(); readonly Label status=new(),summary=new(),counter=new();
    readonly Button fix=new(),scan=new(),retry=new(),copyErrors=new(),cancel=new();
    readonly Dictionary<int,Label> states=new(); readonly Dictionary<int,ProgressBar> bars=new(); readonly Dictionary<int,Label> percents=new();
    readonly Dictionary<int,AppHealth> health=new(); readonly Dictionary<int,string> errors=new();
    readonly List<AppItem> selected; CancellationTokenSource? cts; Process? active;
    static readonly HttpClient Http=new(){Timeout=TimeSpan.FromSeconds(8)};
    static readonly Regex PercentRegex=new(@"(?<!\d)(100|[1-9]?\d)\s*%",RegexOptions.Compiled);
    static readonly Regex SizeRegex=new(@"(?<done>[\d.,]+)\s*(?<du>KB|MB|GB)\s*/\s*(?<total>[\d.,]+)\s*(?<tu>KB|MB|GB)",RegexOptions.Compiled|RegexOptions.IgnoreCase);
    static string Fav(string d)=>$"https://www.google.com/s2/favicons?domain={d}&sz=128";
    static AppItem A(int i,string n,string p,string d)=>new(i,n,p,Fav(d));
    static readonly AppItem[] Catalog={
A(0,"Google Chrome","Google.Chrome","google.com"),A(1,"Mozilla Firefox","Mozilla.Firefox","mozilla.org"),A(2,"Microsoft Edge","Microsoft.Edge","microsoft.com"),A(3,"Brave","Brave.Brave","brave.com"),A(4,"Opera","Opera.Opera","opera.com"),A(5,"Vivaldi","Vivaldi.Vivaldi","vivaldi.com"),
A(6,"Discord","Discord.Discord","discord.com"),A(7,"Telegram","Telegram.TelegramDesktop","telegram.org"),A(8,"Slack","SlackTechnologies.Slack","slack.com"),A(9,"Zoom","Zoom.Zoom","zoom.us"),A(10,"Microsoft Teams","Microsoft.Teams","microsoft.com"),A(11,"Steam","Valve.Steam","steampowered.com"),A(12,"Epic Games Launcher","EpicGames.EpicGamesLauncher","epicgames.com"),A(13,"Prism Launcher","PrismLauncher.PrismLauncher","prismlauncher.org"),A(14,"Heroic Games Launcher","HeroicGamesLauncher.HeroicGamesLauncher","heroicgameslauncher.com"),
A(15,"VLC media player","VideoLAN.VLC","videolan.org"),A(16,"Spotify","Spotify.Spotify","spotify.com"),A(17,"OBS Studio","OBSProject.OBSStudio","obsproject.com"),A(18,"Audacity","Audacity.Audacity","audacityteam.org"),A(19,"HandBrake","HandBrake.HandBrake","handbrake.fr"),A(20,"Visual Studio Code","Microsoft.VisualStudioCode","code.visualstudio.com"),A(21,"Git","Git.Git","git-scm.com"),A(22,"GitHub Desktop","GitHub.GitHubDesktop","desktop.github.com"),A(23,"Python 3","Python.Python.3.13","python.org"),A(24,"Node.js LTS","OpenJS.NodeJS.LTS","nodejs.org"),A(25,"Docker Desktop","Docker.DockerDesktop","docker.com"),A(26,"Postman","Postman.Postman","postman.com"),A(27,"PyCharm Community","JetBrains.PyCharm.Community","jetbrains.com"),A(28,"IntelliJ IDEA Community","JetBrains.IntelliJIDEA.Community","jetbrains.com"),A(29,"Notepad++","Notepad++.Notepad++","notepad-plus-plus.org"),A(30,"Cisco Packet Tracer","url:https://www.netacad.com/learning-collections/cisco-packet-tracer","cisco.com"),A(31,"Blockbench","JannisX11.Blockbench","blockbench.net"),
A(32,"LibreOffice","TheDocumentFoundation.LibreOffice","libreoffice.org"),A(33,"Obsidian","Obsidian.Obsidian","obsidian.md"),A(34,"Thunderbird","Mozilla.Thunderbird","thunderbird.net"),A(35,"Krita","KDE.Krita","krita.org"),A(36,"GIMP","GIMP.GIMP.3","gimp.org"),A(37,"Blender","BlenderFoundation.Blender","blender.org"),A(38,"Inkscape","Inkscape.Inkscape","inkscape.org"),A(39,"ShareX","ShareX.ShareX","getsharex.com"),A(40,"7-Zip","7zip.7zip","7-zip.org"),A(41,"PeaZip","Giorgiotani.Peazip","peazip.github.io"),A(42,"WinRAR","RARLab.WinRAR","rarlab.com"),A(43,"qBittorrent","qBittorrent.qBittorrent","qbittorrent.org"),A(44,"FileZilla","TimKosse.FileZilla.Client","filezilla-project.org"),A(45,"WinSCP","WinSCP.WinSCP","winscp.net"),A(46,"Bitwarden","Bitwarden.Bitwarden","bitwarden.com"),A(47,"KeePassXC","KeePassXCTeam.KeePassXC","keepassxc.org"),A(48,"Malwarebytes","Malwarebytes.Malwarebytes","malwarebytes.com"),
A(49,"PowerToys","Microsoft.PowerToys","microsoft.com"),A(50,"Everything","voidtools.Everything","voidtools.com"),A(51,"WizTree","AntibodySoftware.WizTree","diskanalyzer.com"),A(52,"Rufus","Rufus.Rufus","rufus.ie"),A(53,"balenaEtcher","Balena.Etcher","balena.io"),A(54,"MiniTool Partition Wizard","MiniTool.PartitionWizard.Free","partitionwizard.com"),A(55,"HWiNFO","REALiX.HWiNFO","hwinfo.com"),A(56,"CPU-Z","CPUID.CPU-Z","cpuid.com"),A(57,"CrystalDiskInfo","CrystalDewWorld.CrystalDiskInfo","crystalmark.info"),A(58,"AnyDesk","AnyDeskSoftwareGmbH.AnyDesk","anydesk.com"),A(59,"TeamViewer","TeamViewer.TeamViewer","teamviewer.com"),A(60,"PuTTY","PuTTY.PuTTY","putty.org"),A(61,"RustDesk","RustDesk.RustDesk","rustdesk.com"),A(62,"Visual C++ Redistributable 2015–2022 x64","Microsoft.VCRedist.2015+.x64","microsoft.com"),A(63,".NET Desktop Runtime 8","Microsoft.DotNet.DesktopRuntime.8","dotnet.microsoft.com"),A(64,"Java 21 (Temurin JDK)","EclipseAdoptium.Temurin.21.JDK","adoptium.net"),A(65,"Java 17 (Temurin JDK)","EclipseAdoptium.Temurin.17.JDK","adoptium.net"),A(66,"NVIDIA Graphics Drivers","url:https://www.nvidia.com/Download/index.aspx","nvidia.com"),A(67,"NVIDIA App","url:https://www.nvidia.com/en-us/software/nvidia-app/","nvidia.com"),A(68,"AMD Radeon Drivers","url:https://www.amd.com/en/support/download/drivers.html","amd.com"),A(69,"AMD Software: Adrenalin Edition","url:https://www.amd.com/en/products/software/adrenalin.html","amd.com")};

    public MainForm(){selected=ReadSelection();Text="AppForge — FIX MY SETUP";StartPosition=FormStartPosition.CenterScreen;MinimumSize=new Size(860,650);Size=new Size(1040,780);BackColor=Color.FromArgb(7,15,27);ForeColor=Color.White;Font=new Font("Segoe UI",10);try{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);}catch{} BuildUi();Shown+=async(_,_)=>{if(selected.Count>0)await ScanAsync();};}

    void BuildUi(){
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(26),RowCount=7,ColumnCount=1,BackColor=BackColor};root.RowStyles.Add(new(SizeType.AutoSize));root.RowStyles.Add(new(SizeType.AutoSize));root.RowStyles.Add(new(SizeType.AutoSize));root.RowStyles.Add(new(SizeType.AutoSize));root.RowStyles.Add(new(SizeType.Percent,100));root.RowStyles.Add(new(SizeType.AutoSize));root.RowStyles.Add(new(SizeType.AutoSize));Controls.Add(root);
        var title=new Label{AutoSize=true,Text="AppForge  •  FIX MY SETUP",Font=new Font("Segoe UI",28,FontStyle.Bold),ForeColor=Color.White};root.Controls.Add(title);
        var sub=new Label{AutoSize=true,Text=selected.Count>0?"Scanning your selected apps: missing → install, old → update, current → skip.":"No website selection found. Download a fresh AppForge setup from the website.",ForeColor=Color.FromArgb(155,170,191),Margin=new Padding(0,2,0,10)};root.Controls.Add(sub);
        summary.AutoSize=true;summary.Text=selected.Count>0?"PC Health: waiting for scan…":"Selection missing";summary.ForeColor=Color.FromArgb(103,210,255);summary.Font=new Font("Segoe UI",10,FontStyle.Bold);summary.Margin=new Padding(0,0,0,10);root.Controls.Add(summary);
        var tools=new FlowLayoutPanel{AutoSize=true,Dock=DockStyle.Fill,FlowDirection=FlowDirection.LeftToRight,Margin=new Padding(0,0,0,10)};StyleButton(scan,"Scan again",false);StyleButton(retry,"Retry failed",false);StyleButton(copyErrors,"Copy errors",false);StyleButton(cancel,"Cancel",false);scan.Click+=async(_,_)=>await ScanAsync();retry.Click+=async(_,_)=>await FixAsync(true);copyErrors.Click+=(_,_)=>CopyErrors();cancel.Click+=(_,_)=>{cts?.Cancel();try{active?.Kill(true);}catch{}};retry.Enabled=false;copyErrors.Enabled=false;cancel.Enabled=false;tools.Controls.AddRange([scan,retry,copyErrors,cancel]);root.Controls.Add(tools);
        appList.Dock=DockStyle.Fill;appList.FlowDirection=FlowDirection.TopDown;appList.WrapContents=false;appList.AutoScroll=true;appList.BackColor=Color.FromArgb(10,22,37);appList.Padding=new Padding(12);root.Controls.Add(appList);
        if(selected.Count>0)foreach(var a in selected)AddRow(a);else appList.Controls.Add(new Label{Width=900,Height=100,Text="Go back to AppForge → choose apps → Get my apps → download a fresh installer.",TextAlign=ContentAlignment.MiddleCenter,ForeColor=Color.FromArgb(155,170,191)});
        var pr=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,AutoSize=true,Margin=new Padding(0,14,0,8)};pr.ColumnStyles.Add(new(SizeType.Percent,100));pr.ColumnStyles.Add(new(SizeType.AutoSize));overall.Dock=DockStyle.Fill;overall.Height=16;counter.AutoSize=true;counter.Text=$"0 / {selected.Count}";counter.ForeColor=Color.FromArgb(155,170,191);counter.Margin=new Padding(12,0,0,0);pr.Controls.Add(overall,0,0);pr.Controls.Add(counter,1,0);root.Controls.Add(pr);
        var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,AutoSize=true};bottom.ColumnStyles.Add(new(SizeType.Percent,100));bottom.ColumnStyles.Add(new(SizeType.AutoSize));status.AutoSize=true;status.Text=selected.Count>0?"Checking PC…":"Selection missing";status.ForeColor=Color.FromArgb(155,170,191);StyleButton(fix,"FIX MY SETUP",true);fix.Enabled=false;fix.Click+=async(_,_)=>await FixAsync(false);bottom.Controls.Add(status,0,0);bottom.Controls.Add(fix,1,0);root.Controls.Add(bottom);
    }
    void StyleButton(Button b,string text,bool primary){b.Text=text;b.AutoSize=true;b.Padding=new Padding(16,8,16,8);b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderSize=primary?0:1;b.FlatAppearance.BorderColor=Color.FromArgb(53,70,92);b.BackColor=primary?Color.FromArgb(82,219,255):Color.FromArgb(14,27,45);b.ForeColor=primary?Color.FromArgb(5,17,29):Color.White;b.Font=new Font("Segoe UI",9.5f,primary?FontStyle.Bold:FontStyle.Regular);b.Margin=new Padding(0,0,8,0);}
    void AddRow(AppItem a){var p=new Panel{Width=910,Height=74,Margin=new Padding(0,0,0,7),BackColor=Color.FromArgb(16,31,50)};var pic=new PictureBox{Location=new Point(14,12),Size=new Size(40,40),SizeMode=PictureBoxSizeMode.Zoom};var n=new Label{Text=a.Name,AutoSize=true,Location=new Point(70,9),Font=new Font("Segoe UI",10,FontStyle.Bold),ForeColor=Color.White};var d=new Label{Text=a.PackageId.StartsWith("url:")?"Official vendor page":"Verified package ID: "+a.PackageId,AutoSize=true,Location=new Point(70,31),Font=new Font("Segoe UI",8),ForeColor=Color.FromArgb(140,157,179)};var bar=new ProgressBar{Location=new Point(70,54),Size=new Size(610,9),Maximum=100};var pct=new Label{Text="0%",Location=new Point(690,49),Width=50,Height=20,TextAlign=ContentAlignment.MiddleRight,ForeColor=Color.FromArgb(155,170,191)};var st=new Label{Text="Waiting",Location=new Point(750,24),Width=140,Height=24,TextAlign=ContentAlignment.MiddleRight,ForeColor=Color.FromArgb(155,170,191),Font=new Font("Segoe UI",9,FontStyle.Bold)};states[a.Index]=st;bars[a.Index]=bar;percents[a.Index]=pct;health[a.Index]=AppHealth.Unknown;p.Controls.AddRange([pic,n,d,bar,pct,st]);appList.Controls.Add(p);_=LoadIcon(pic,a.IconUrl);}
    static async Task LoadIcon(PictureBox b,string u){try{var x=await Http.GetByteArrayAsync(u);using var ms=new MemoryStream(x);using var im=Image.FromStream(ms);if(!b.IsDisposed)b.Image=new Bitmap(im);}catch{}}

    async Task ScanAsync(){if(selected.Count==0)return;SetBusy(true,"Scanning PC…");errors.Clear();int missing=0,current=0,updates=0,manual=0,failed=0,done=0;overall.Maximum=selected.Count;overall.Value=0;
        foreach(var a in selected){if(a.PackageId.StartsWith("url:")){health[a.Index]=AppHealth.Manual;manual++;SetState(a,0,"Manual page",Color.FromArgb(244,196,95));}else{try{var list=await RunCapture("winget",$"list --id \"{a.PackageId}\" -e --accept-source-agreements --disable-interactivity");if(!LooksInstalled(list)){health[a.Index]=AppHealth.Missing;missing++;SetState(a,0,"Missing ↓",Color.FromArgb(103,210,255));}else{var up=await RunCapture("winget",$"upgrade --id \"{a.PackageId}\" -e --accept-source-agreements --disable-interactivity");if(HasUpgrade(up)){health[a.Index]=AppHealth.Update;updates++;SetState(a,0,"Update available ↑",Color.FromArgb(244,196,95));}else{health[a.Index]=AppHealth.Current;current++;SetState(a,100,"Already good ✓",Color.FromArgb(111,231,183));}}}catch(Exception ex){health[a.Index]=AppHealth.Failed;failed++;errors[a.Index]=ex.Message;SetState(a,0,"Scan failed",Color.FromArgb(255,120,130));}}done++;overall.Value=done;counter.Text=$"{done} / {selected.Count}";}
        summary.Text=$"PC Health: {current} good ✓  •  {updates} update ↑  •  {missing} missing ↓  •  {manual} manual{(failed>0?$"  •  {failed} scan failed":"")}";fix.Enabled=missing+updates+manual>0;retry.Enabled=failed>0;copyErrors.Enabled=failed>0;SetBusy(false,missing+updates+manual==0?"Your selected setup is already healthy ✓":"Ready — press FIX MY SETUP");WriteLog("SCAN",summary.Text);}
    static bool LooksInstalled(string s)=>!string.IsNullOrWhiteSpace(s)&&!s.Contains("No installed package found",StringComparison.OrdinalIgnoreCase)&&!s.Contains("No package found",StringComparison.OrdinalIgnoreCase);
    static bool HasUpgrade(string s)=>!string.IsNullOrWhiteSpace(s)&&!s.Contains("No applicable upgrade found",StringComparison.OrdinalIgnoreCase)&&!s.Contains("No available upgrade found",StringComparison.OrdinalIgnoreCase)&&!s.Contains("No installed package found",StringComparison.OrdinalIgnoreCase)&&s.Contains("Version",StringComparison.OrdinalIgnoreCase)&&s.Contains("Available",StringComparison.OrdinalIgnoreCase);

    async Task FixAsync(bool failedOnly){if(selected.Count==0)return;cts=new();errors.Clear();SetBusy(true,"Fixing setup…");cancel.Enabled=true;var targets=failedOnly?selected.Where(a=>health.GetValueOrDefault(a.Index)==AppHealth.Failed).ToList():selected.Where(a=>health.GetValueOrDefault(a.Index) is AppHealth.Missing or AppHealth.Update or AppHealth.Manual or AppHealth.Failed).ToList();overall.Maximum=Math.Max(1,targets.Count);overall.Value=0;int installed=0,updated=0,skipped=selected.Count-targets.Count,opened=0,failed=0,done=0;
        foreach(var a in targets){if(cts.IsCancellationRequested)break;try{var h=health.GetValueOrDefault(a.Index);if(a.PackageId.StartsWith("url:")){Process.Start(new ProcessStartInfo(a.PackageId[4..]){UseShellExecute=true});opened++;SetState(a,100,"Official page opened",Color.FromArgb(244,196,95));}else{string verb=h==AppHealth.Update?"upgrade":"install";SetState(a,0,verb=="upgrade"?"Updating…":"Installing…",Color.FromArgb(103,210,255));var code=await RunWinget(a,verb,cts.Token);if(code==0){if(verb=="upgrade")updated++;else installed++;health[a.Index]=AppHealth.Current;SetState(a,100,verb=="upgrade"?"Updated ✓":"Installed ✓",Color.FromArgb(111,231,183));}else{failed++;health[a.Index]=AppHealth.Failed;errors[a.Index]=$"Winget exit code {code}";SetState(a,bars[a.Index].Value,"Failed ✕",Color.FromArgb(255,120,130));}}}catch(OperationCanceledException){break;}catch(Exception ex){failed++;health[a.Index]=AppHealth.Failed;errors[a.Index]=ex.Message;SetState(a,bars[a.Index].Value,"Failed ✕",Color.FromArgb(255,120,130));}done++;overall.Value=Math.Min(overall.Maximum,done);counter.Text=$"{done} / {targets.Count}";}
        cancel.Enabled=false;SetBusy(false,cts.IsCancellationRequested?"Cancelled":$"SETUP FIXED — {installed} installed • {updated} updated • {skipped} already good • {opened} manual • {failed} failed");summary.Text=status.Text;retry.Enabled=failed>0;copyErrors.Enabled=failed>0;fix.Enabled=false;WriteLog("FIX",status.Text);}
    async Task<int> RunWinget(AppItem a,string verb,CancellationToken token){var args=$"{verb} --id \"{a.PackageId}\" -e --silent --accept-package-agreements --accept-source-agreements --disable-interactivity";var psi=new ProcessStartInfo("winget",args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};using var p=new Process{StartInfo=psi};active=p;p.Start();var o=ReadProgress(p.StandardOutput,a,token);var e=ReadProgress(p.StandardError,a,token);await p.WaitForExitAsync(token);await Task.WhenAll(o,e);return p.ExitCode;}
    async Task ReadProgress(StreamReader r,AppItem a,CancellationToken t){while(!r.EndOfStream&&!t.IsCancellationRequested){var line=await r.ReadLineAsync(t);if(string.IsNullOrWhiteSpace(line))continue;var pct=ExtractPercent(line);if(pct.HasValue)BeginInvoke(()=>SetState(a,pct.Value,$"Downloading {pct}%",Color.FromArgb(103,210,255)));else if(line.Contains("Installing",StringComparison.OrdinalIgnoreCase))BeginInvoke(()=>SetState(a,bars[a.Index].Value,"Installing…",Color.FromArgb(103,210,255)));}}
    static async Task<string> RunCapture(string file,string args){var psi=new ProcessStartInfo(file,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};using var p=Process.Start(psi)??throw new Exception("Could not start Windows Package Manager.");var o=await p.StandardOutput.ReadToEndAsync();var e=await p.StandardError.ReadToEndAsync();await p.WaitForExitAsync();return o+"\n"+e;}
    static int? ExtractPercent(string s){var m=PercentRegex.Match(s);if(m.Success&&int.TryParse(m.Groups[1].Value,out var x))return Math.Clamp(x,0,100);var z=SizeRegex.Match(s);if(!z.Success)return null;if(!double.TryParse(z.Groups["done"].Value.Replace(',','.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var d)||!double.TryParse(z.Groups["total"].Value.Replace(',','.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var t))return null;double U(string u)=>u.ToUpperInvariant() switch{"GB"=>1048576,"MB"=>1024,_=>1};d*=U(z.Groups["du"].Value);t*=U(z.Groups["tu"].Value);return t<=0?null:Math.Clamp((int)Math.Round(d/t*100),0,100);}
    void SetState(AppItem a,int pct,string text,Color c){if(bars.TryGetValue(a.Index,out var b))b.Value=Math.Clamp(pct,0,100);if(percents.TryGetValue(a.Index,out var p))p.Text=$"{Math.Clamp(pct,0,100)}%";if(states.TryGetValue(a.Index,out var s)){s.Text=text;s.ForeColor=c;}status.Text=$"{a.Name}: {text}";}
    void SetBusy(bool busy,string text){scan.Enabled=!busy;fix.Enabled=!busy&&fix.Enabled;status.Text=text;UseWaitCursor=busy;}
    void CopyErrors(){if(errors.Count==0)return;var text=string.Join(Environment.NewLine,errors.Select(kv=>$"{Catalog.First(a=>a.Index==kv.Key).Name}: {kv.Value}"));try{Clipboard.SetText(text);status.Text="Errors copied ✓";}catch{status.Text="Could not copy errors";}}
    static void WriteLog(string type,string text){try{var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AppForge");Directory.CreateDirectory(dir);File.AppendAllText(Path.Combine(dir,"history.log"),$"{DateTime.Now:yyyy-MM-dd HH:mm:ss} [{type}] {text}{Environment.NewLine}");}catch{}}

    static List<AppItem> ReadSelection(){try{var n=Path.GetFileNameWithoutExtension(Application.ExecutablePath);const string pre="AppForge-";if(n.StartsWith(pre,StringComparison.OrdinalIgnoreCase)){var raw=n[pre.Length..];var token=raw.Split("--",2)[0];var paren=token.IndexOf(" (");if(paren>=0)token=token[..paren];token=token.Replace('-','+').Replace('_','/');token+=(token.Length%4) switch{2=>"==",3=>"=",_=>""};var bits=Convert.FromBase64String(token);var ids=new HashSet<int>();for(int i=0;i<bits.Length*8;i++)if((bits[i/8]&(1<<(i%8)))!=0)ids.Add(i);var r=Catalog.Where(a=>ids.Contains(a.Index)).ToList();if(r.Count>0)return r;}}catch{}
        try{var bytes=File.ReadAllBytes(Application.ExecutablePath);var marker=Encoding.UTF8.GetBytes("\nAPPFORGE_SELECTION_V1:");var end=Encoding.UTF8.GetBytes(":END\n");int s=Last(bytes,marker);if(s<0)return[];s+=marker.Length;int e=Find(bytes,end,s);if(e<=s)return[];var ids=Encoding.UTF8.GetString(bytes,s,e-s).Split('.',StringSplitOptions.RemoveEmptyEntries).Select(x=>int.TryParse(x,out var i)?i:-1).Where(i=>i>=0).ToHashSet();return Catalog.Where(a=>ids.Contains(a.Index)).ToList();}catch{return[];}}
    static int Last(byte[] s,byte[] p){for(int i=s.Length-p.Length;i>=0;i--){bool ok=true;for(int j=0;j<p.Length;j++)if(s[i+j]!=p[j]){ok=false;break;}if(ok)return i;}return-1;}static int Find(byte[] s,byte[] p,int start){for(int i=start;i<=s.Length-p.Length;i++){bool ok=true;for(int j=0;j<p.Length;j++)if(s[i+j]!=p[j]){ok=false;break;}if(ok)return i;}return-1;}
}